## Task 1: 
 
  1.Write a function to compute 5/0 and use try/except to catch the exceptions. 
 
 

In [2]:
def compute():
    try:
        i=5/0
        print(i)
    except Exception as e:
        print(e)
compute()

division by zero


2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket. 

In [67]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]



result = [s+" " + v + " " + o +"." for s in subjects for v in verbs for o in objects]

#print([s+" " + v + " " + o +"."] for s in subjects for v in verbs for o in objects)
b=""
for r in result:
    print(str(r))

print(b)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.



## 2.1 
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 
 
 
NOTE:​ ​The​ ​solution​ ​shared​ ​through​ ​Github​ ​should​ ​contain​ ​the​ ​source code​ ​used​ ​and​ ​the​ ​screenshot​ ​of​ ​the​ ​output. 

In [66]:
import numpy as np

def powerarray():
    N=4
    x=np.array([1,2,3,4])
    print(np.column_stack([x**(N-1-i) for i in range(N)]))
powerarray()


[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
